### ISSUE TITLE
Script creating of service accounts to GCP

### ISSUE THREAD

**Issue by mtmcduffie** [dfci/cidc-devops#15]

**Comment by lemccarthy** [comment]
What is the scope of this issue @mtmcduffie ? I already programmatically create some service accounts. Which one specifically needs to be scripted?

**Comment by mtmcduffie** [comment]
How about the scope is what you have already, and we'll backlog the remainder?

**Comment by mtmcduffie** [comment]
I was confused, I thought we were using GCP Service accounts more than we are.
