### ISSUE TITLE
Ensure there is a markdown document explaining the code change / gitflow / deployment process.

### ISSUE THREAD

**Issue by mtmcduffie** [dfci/cidc-devops#65]
This should also have mention of where unit and or integration tests are running.

**Comment by mtmcduffie** [comment]
Written is fine for now, I'll do a diagram based on your text.

**Comment by lemccarthy** [comment]
https://github.com/dfci/cidc-devops/commit/e6ce0a61b54a3f40ecf1791a35c8c18bb6cde3a0 has the first implementation of this
