### ISSUE TITLE
Document process of restoring MongoDB from backup.

### ISSUE THREAD

**Issue by mtmcduffie** [dfci/cidc-devops#67]

**Comment by lemccarthy** [comment]
Added in https://github.com/dfci/cidc-devops/commit/5293096dd626962659ec745bf32fab4022c2198f

**Comment by mtmcduffie** [comment]
https://github.com/dfci/cidc-devops/commit/8f964c11d6f0408e2e84d2799ebac425a1c2de32#diff-df014101b9516f7b3acd8cee94c639b9
